// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type User struct {
	ID         string
	Username   sql.NullString
	Password   sql.NullString
	Role       sql.NullString
	ResetToken sql.NullString
	IsActive   sql.NullString
}
